export const ProductData = [
  {
    id: 1001,
    name: "Roulette Chicken",
    title: "boneless chicken breasts",
    price: 13,
    quantity: 1,
    img: require("../images/pic(1).png"),
  },
  {
    id: 1002,
    name: "Grill Mushroom",
    title: "boneless chicken breasts",
    price: 17,
    quantity: 1,
    img: require("../images/pic(2).png"),
  },
  {
    id: 1003,
    name: "Nacho Chicken",
    title: "boneless chicken breasts",
    price: 15,
    quantity: 1,
    img: require("../images/pic(3).png"),
  },
  {
    id: 1004,
    name: "Grill,Tikka Masala",
    title: "boneless chicken breasts",
    price: 26,
    quantity: 1,
    img: require("../images/pic(4).png"),
  },
  {
    id: 1005,
    name: "Chicken Grill",
    title: "boneless chicken breasts",
    price: 21,
    quantity: 1,
    img: require("../images/pic(5).png"),
  },
  {
    id: 1006,
    name: "Chicken Tikka",
    title: "boneless chicken breasts",
    price: 22,
    quantity: 1,
    img: require("../images/pic(6).png"),
  },
];
